### ISSUE TITLE
Descrambling fails

### ISSUE THREAD

**Issue by j4nos** [3rdIteration/btcrecover#123] opened 2021-02-09 22:58 UTC
I would run the example from this tutorial, but it fails. Do you have any deja why?

```
python3 seedrecover.py --no-dupchecks --mnemonic-length 12 --language EN --dsw --wallet-type BIP39 --addr-limit 1 --addrs 17GR7xWtWrfYm6y3xoZy8cXioVqBbSYcpU --tokenlist ./btcrecover/test/test-listfiles/SeedTokenListTest.txt
```

https://github.com/3rdIteration/btcrecover/blob/master/docs/BIP39_descrambling_seedlists.md

```
btcrecover-master kukodajanos$ python3 seedrecover.py --no-dupchecks --mnemonic-length 12 --language EN --dsw --wallet-type BIP39 --addr-limit 1 --addrs 17GR7xWtWrfYm6y3xoZy8cXioVqBbSYcpU --tokenlist ./btcrecover/test/test-listfiles/SeedTokenListTest.txt

Starting seedrecover 1.7.0-CryptoGuide, btcrecover 1.7.0-Cryptoguide on Python 3.9.1 64-bit, 21-bit unicodes, 64-bit ints
Using the 'en' wordlist.
2021-02-09 23:55:37 : Phase 1/1: up to 12 mistakes, 12 of which can be an entirely different seed word.

Interrupted after counting 0 passwords 
Traceback (most recent call last):
  File "/Users/kukodajanos/Downloads/btcrecover-master/seedrecover.py", line 38, in <module>
    mnemonic_sentence, path_coin = btcrseed.main(sys.argv[1:])
  File "/Users/kukodajanos/Downloads/btcrecover-master/btcrecover/btcrseed.py", line 2656, in main
    mnemonic_found = run_btcrecover(**phase_params)
  File "/Users/kukodajanos/Downloads/btcrecover-master/btcrecover/btcrseed.py", line 2083, in run_btcrecover
    (mnemonic_found, not_found_msg) = btcrpass.main()
  File "/Users/kukodajanos/Downloads/btcrecover-master/btcrecover/btcrpass.py", line 6369, in main
    passwords_count = count_and_check_eta(est_secs_per_password)
  File "/Users/kukodajanos/Downloads/btcrecover-master/btcrecover/btcrpass.py", line 6120, in count_and_check_eta
    return password_generator_factory(est_secs_per_password = est)[1]
  File "/Users/kukodajanos/Downloads/btcrecover-master/btcrecover/btcrpass.py", line 6156, in password_generator_factory
    for passwords_counted_last in passwords_count_iterator:
  File "/Users/kukodajanos/Downloads/btcrecover-master/btcrecover/btcrpass.py", line 4959, in password_generator
    for password_base in base_password_generator() if callable(base_password_generator) else base_password_generator:
  File "/Users/kukodajanos/Downloads/btcrecover-master/btcrecover/btcrpass.py", line 5089, in tokenlist_base_password_generator
    if args.keep_tokens_order:
AttributeError: 'Namespace' object has no attribute 'keep_tokens_order'
```

**Comment by 3rdIteration** [comment] 2021-02-09 23:01
Duplicate of https://github.com/3rdIteration/btcrecover/issues/121

Should be fixed now if you download the updated repo.

**Closed by 3rdIteration** 2021-02-09 23:01 UTC
