### ISSUE TITLE
        if xprv.startswith(b"xprv"):  # BIP32 extended private key version bytes

### ISSUE THREAD

**Issue by arashjooooon** [3rdIteration/btcrecover#459] opened 2024-03-25 20:05 UTC
if xprv.startswith(b"xprv"):  # BIP32 extended private key version bytes

**Comment by 3rdIteration** [comment] 2024-03-26 22:02
If you have an xprv then you don't need BTCRecover. What are you attempting to do?

**Comment by 3rdIteration** [comment] 2024-06-18 00:06
Looks like duplicate of https://github.com/3rdIteration/btcrecover/issues/457

**Closed by 3rdIteration** 2024-06-18 00:06 UTC
Labels: duplicate
