### ISSUE TITLE
seedrecovery.py running with a 3090 warning error

### ISSUE THREAD

**Issue by joelqc1** [3rdIteration/btcrecover#466] opened 2024-04-24 14:49 UTC
I have this error, when i have been working for some minutes.

Any idea someone? Also what it means "warning generated"? Where i can see the warning.

Thank's!

1 x NVIDIA RTX 3090 24GB
1 x i3-10100 CPU @ 3.60GHz
8GB RAM DDR4

```

2024-04-24 15:25:53 : Using 8 worker threads
Killed47200  elapsed: 0:45:20  rate: 100.33 kP/s
root@hive1008:~/seed/btcrecover# Process SpawnPoolWorker-4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process SpawnPoolWorker-5:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 7 leaked semaphores to clean up at shutdown
  len(cache))`
```

**Comment by 3rdIteration** [comment] 2024-04-24 20:12
Yea these warnings are normal with the latest drivers, everything still works normally though. 

What kind of recovery you doing? Does enabling --no-dupchecks fix it? (You are probably just running out of memory)

**Comment by joelqc1** [comment] 2024-04-24 21:46
Yes dupchecks enabled, when i have that error the process ends. And i lose all the job done :C

I'm recovering 3 words from a 12 word seed phrase. 

Now in another server:
i5 12vCPUs
6 x 3090
32GB RAM

```
python3 seedrecover.py --wallet-type bip39 --addrs "zzzzzzzzzzzzzzzzz" --no-dupchecks --tokenlist tokenlist.txt --addr-limit 10 --mnemonic-length 12 --bip32-path "m/44'/0'/0'/0/0" --language en --no-eta
``` 
I'm not sure if the gpu are working allright, due to without "--enable-opencl" i'm running 48 kP/s. 

```
python3 seedrecover.py --wallet-type bip39 --addrs "zzzzzzzzzzzzzzzzz"--no-dupchecks --tokenlist tokenlist.txt --addr-limit 10 --mnemonic-length 12 --bip32-path "m/44'/0'/0'/0/0" --language en --no-eta --enable-opencl --opencl-devices 0 1 2 3 4 5 --threads 10
``` 
But with opencl enabled and 6 x 3090, with thread limit at 10, it works at 100-120 kP/s, lookint at the resources used of the gpus, any gpu is working at all.

**Comment by 3rdIteration** [comment] 2024-04-24 22:53
So why are you using tokenlists and GPU if just recovering three missing words? If you know the position of the words it's a straightforward recovery that will be done in a day or less on that cpu?

**Comment by 3rdIteration** [comment] 2024-04-24 23:25
That isn't how you should be doing this, but this isn't a support channel.

Python 3.8 also isn't supported, so try with a newer version and see if the issue persists.

**Comment by 3rdIteration** [comment] 2024-06-18 00:56
Duplicate of https://github.com/3rdIteration/btcrecover/issues/467

**Closed by 3rdIteration** 2024-06-18 00:56 UTC
Labels: duplicate
