### ISSUE TITLE
What value should I specify for the --skip parameter on the third run?

### ISSUE THREAD

**Issue by Grayesso** [3rdIteration/btcrecover#444] opened 2024-02-07 18:01 UTC
Can be shown using any example.
Here in the photo you can see that I ran it a second time with --skip 6,248,879,162.
And I have already checked 993,536,896 passwords.
If I stop it now, it shows that it has stopped at the password 993536896.
Question for you now:
When I run it for the third time, what --skip option should I specify?

from here it is clear that “--skip 993,536,896” will be incorrect, since “6,248,879,162” is greater than 993,536,896 (almost 6 times)
Why don't these numbers add up during a forced stop for the next launch?

or

Why does the countdown start from 1 on the second run and not from “6,248,879,162”? If it started with the number specified in --skip at each subsequent stop after checks would it show the sum of the previous number "6 248 879 162" and the amount passed on the current start after the stop "7 242 416 058"?

6,248,879,162 + 993,536,896 = 7,242,416,058
![scrine](https://github.com/3rdIteration/btcrecover/assets/94595794/563a813b-fe71-4e28-89d0-911b157cd37a)

**Comment by 3rdIteration** [comment] 2024-02-07 18:47
Duplicate of https://github.com/3rdIteration/btcrecover/issues/443

You need to provide an example tokenlist, test wallet and command used to reproduce

**Comment by Grayesso** [comment] 2024-02-07 19:07
> Duplicate of #443
> 
> You need to provide an example tokenlist, test wallet and command used to reproduce

this has nothing to do with the test wallet, tokenlist or address. Everything I wrote and in the photo, everything is clear what I mean

**Comment by 3rdIteration** [comment] 2024-02-07 19:39
I have generated multiple test lists and the skip commands work as expected. (For example a simple tokenlist %2d that will produce 100 passwords, if you skip 10, you will get 90... And cav verify what is being generated with listpass)

If you are looking at seed recovery with tokenlists then the speed will vary depending on what proportion of the seeds are valid, etc.

So basically you need to provide something that allows someone else to reproduce the bug that you believe is occurring.

**Comment by Grayesso** [comment] 2024-02-07 20:36
In my command in the photo, the --skip option does what? What is it for?

**Comment by 3rdIteration** [comment] 2024-02-07 20:47
It's skips N passwords/seeds.

It doesn't look like there is a bug here unless you can provide a test wallet and sample tokenlist that allow the behaviour to be reproduced.

**Comment by Grayesso** [comment] 2024-02-08 19:37
> It's skips N passwords/seeds.
> 
> It doesn't look like there is a bug here unless you can provide a test wallet and sample tokenlist that allow the behaviour to be reproduced.

skips the number of verified passwords on the previous launch?

**Comment by 3rdIteration** [comment] 2024-02-09 23:42
Working as intended

**Closed by 3rdIteration** 2024-02-09 23:42 UTC
