### ISSUE TITLE
Ubuntu 20,04 test stuck

### ISSUE THREAD

**Issue by europound** [3rdIteration/btcrecover#108] opened 2021-02-01 10:14 UTC
test_restore_changed_data_extract
.   test_restore_changed_tokenlist
.   test_restore_truncated
  Test07WalletDecryption
E   test_Electrum28_OpenCL_Brute
    test_androidpin
wallets@wallets-TUF-Gaming:~/Downloads/btcrecover-master$ python run-all-tests.py -vv
Testing seedrecover 1.5.0-CryptoGuide, btcrecover 1.6.0-Cryptoguide on Python 3.8.5 64-bit, 21-bit unicodes, 64-bit ints

** Testing in Unicode character mode **
btcrecover.test.test_passwords
  Test01Basics
.   test_alternate
.   test_alternate_unicode
.   test_chunksize_divisible
.   test_chunksize_indivisible
.   test_chunksize_modified
.   test_comments
.   test_count
.   test_count_one_chunk
.   test_count_two_chunks
.   test_count_zero
.   test_empty_file
.   test_mutex
.   test_one_char_file
.   test_only_yield_count
.   test_only_yield_count_all
.   test_require
.   test_token_counts_max_2
.   test_token_counts_min_0
.   test_token_counts_min_2
.   test_token_counts_min_max_2
.   test_z_all
  Test02Anchors
.   test_begin
.   test_begin_0len
.   test_begin_and_end
.   test_end
.   test_end_0len
.   test_middle
.   test_middle_0len
.   test_middle_invalid_begin
.   test_middle_invalid_range
.   test_middle_old
.   test_not_middle
.   test_positional
.   test_positional_0len
.   test_positional_invalid
.   test_positional_old
.   test_relative_one
.   test_relative_same
.   test_relative_two
.   test_tokens_duplicate
  Test03WildCards
.   test_backreference
.   test_backreference_bounds
.   test_backreference_length
.   test_backreference_map
.   test_backreference_map_bounds
.   test_backreference_map_length
.   test_backreference_map_missing
.   test_backreference_map_pos
.   test_backreference_map_pos_length
.   test_backreference_pos
.   test_backreference_pos_length
.   test_basics_1
.   test_basics_2
.   test_basics_3
.   test_basics_4
.   test_case_insensitive_1
.   test_case_insensitive_2
.   test_case_lower
.   test_case_upper
.   test_contracting_1
.   test_contracting_2
.   test_contracting_left
.   test_contracting_multiple
.   test_contracting_right
.   test_custom
.   test_custom_insensitive_1
.   test_custom_insensitive_2
.   test_custom_upper
.   test_invalid_length_1
.   test_invalid_length_2
.   test_invalid_nocust
.   test_invalid_nocust_cap
.   test_invalid_notype
.   test_length_2
.   test_length_invalid_range
.   test_length_range
.   test_multiple
.   test_noset
.   test_range_1
.   test_range_2
.   test_range_insensitive
.   test_range_invalid
.   test_set
.   test_set_insensitive
  Test04Typos
.   test_capslock
.   test_capslock_min_1
.   test_capslock_min_2
.   test_capslock_nocaps
.   test_capslock_unicode
.   test_case
.   test_case_max
.   test_closecase
.   test_closecase_max
.   test_delete
.   test_delete_max
.   test_insert
.   test_insert_adjacent_1
.   test_insert_adjacent_2
.   test_insert_invalid
.   test_insert_max
.   test_insert_min_1
.   test_insert_min_2
.   test_insert_min_5
.   test_insert_wildcard
.   test_insert_wildcard_adjacent
.   test_map
.   test_map_max
.   test_repeat
.   test_repeat_max
.   test_repeat_min_1
.   test_repeat_min_2
.   test_repeat_min_4
.   test_replace
.   test_replace_invalid
.   test_replace_max
.   test_replace_wildcard
.   test_swap
.   test_swap_max
.   test_swap_min_1
.   test_swap_min_2
.   test_swap_min_3
.   test_z_all
.   test_z_all_max
.   test_z_min_typos_1
.   test_z_min_typos_2
  Test05CommandLine
.   test_delimiter_tokenlist
.   test_delimiter_typosmap
.   test_embedded_tokenlist_option
.   test_embedded_tokenlist_option_invalid
.   test_embedded_tokenlist_option_unicode
.   test_embedded_tokenlist_overwridden_option
.   test_exclude
.   test_exclude_nodupchecks
.   test_exclude_noeta
.   test_exclude_noeta_nodupchecks
.   test_max_eta
.   test_max_eta_ok
.   test_max_eta_skip
.   test_max_eta_skip_ok
.   test_no_dupchecks_1
.   test_no_dupchecks_2
.   test_no_dupchecks_3
.   test_passwordlist_no_wildcards
.   test_regex_never
.   test_regex_only
.   test_skip
.   test_skip_all_exact
.   test_skip_all_pastend_1
.   test_skip_all_pastend_2
.   test_skip_empty_1
.   test_skip_empty_2
.   test_skip_end2end
.   test_skip_end2end_all_exact
.   test_skip_end2end_all_noeta
.   test_skip_end2end_all_pastend
.   test_skip_large_1
.   test_skip_large_1_all_exact
.   test_skip_large_1_all_pastend
.   test_skip_large_2
.   test_skip_large_2_all_exact
.   test_skip_large_2_all_pastend
.   test_unicode
.   test_worker_evensplit
.   test_worker_unevensplit
  Test06AutosaveRestore
.   test_autosave
.   test_autosave_restore
.   test_restore
.   test_restore_changed_args
.   test_restore_changed_data_extract
.   test_restore_changed_tokenlist
.   test_restore_truncated
  Test07WalletDecryption
E   test_Electrum28_OpenCL_Brute
    test_androidpin^C^CProcess DaemonlessPoolWorker-12:
Process DaemonlessPoolWorker-11:
Process DaemonlessPoolWorker-14:
Process DaemonlessPoolWorker-2:
Process DaemonlessPoolWorker-13:
Process DaemonlessPoolWorker-16:
Process DaemonlessPoolWorker-6:
Traceback (most recent call last):
  File "run-all-tests.py", line 108, in <module>
Process DaemonlessPoolWorker-9:
Process DaemonlessPoolWorker-10:
Process DaemonlessPoolWorker-15:
Process DaemonlessPoolWorker-4:
Process DaemonlessPoolWorker-8:
Process DaemonlessPoolWorker-7:
Process DaemonlessPoolWorker-5:
Process DaemonlessPoolWorker-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/green/process.py", line 197, in worker
    task = get()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.8/unittest/signals.py", line 36, in __call__
    self.default_handler(signum, frame)
KeyboardInterrupt
    results = main(test_passwords, exit=False, buffer= not args.no_buffer).result
  File "run-all-tests.py", line 45, in main
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/green/process.py", line 197, in worker
    task = get()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.8/unittest/signals.py", line 36, in __call__
    self.default_handler(signum, frame)
Traceback (most recent call last):
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/green/process.py", line 197, in worker
    task = get()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.8/unittest/signals.py", line 36, in __call__
    self.default_handler(signum, frame)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
KeyboardInterrupt
  File "/usr/local/lib/python3.8/dist-packages/green/process.py", line 197, in worker
    task = get()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.8/unittest/signals.py", line 36, in __call__
    self.default_handler(signum, frame)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/green/process.py", line 197, in worker
    task = get()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.8/unittest/signals.py", line 36, in __call__
    self.default_handler(signum, frame)
KeyboardInterrupt
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/green/process.py", line 197, in worker
    task = get()
  File "/usr/local/lib/python3.8/dist-packages/green/process.py", line 197, in worker
    task = get()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 356, in get
    res = self._reader.recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/unittest/signals.py", line 36, in __call__
    self.default_handler(signum, frame)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/usr/lib/python3.8/unittest/signals.py", line 36, in __call__
    self.default_handler(signum, frame)
KeyboardInterrupt
KeyboardInterrupt
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/green/process.py", line 197, in worker
    task = get()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.8/unittest/signals.py", line 36, in __call__
    self.default_handler(signum, frame)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/green/process.py", line 197, in worker
    task = get()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.8/unittest/signals.py", line 36, in __call__
    self.default_handler(signum, frame)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/green/process.py", line 197, in worker
    task = get()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.8/unittest/signals.py", line 36, in __call__
    self.default_handler(signum, frame)
KeyboardInterrupt
    results = green.runner.run(suite, sys.stdout, green_args)
  File "/usr/local/lib/python3.8/dist-packages/green/runner.py", line 136, in run
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/green/process.py", line 197, in worker
    task = get()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.8/unittest/signals.py", line 36, in __call__
    self.default_handler(signum, frame)
KeyboardInterrupt
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/green/process.py", line 197, in worker
    task = get()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.8/unittest/signals.py", line 36, in __call__
    self.default_handler(signum, frame)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/green/process.py", line 197, in worker
    task = get()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.8/unittest/signals.py", line 36, in __call__
    self.default_handler(signum, frame)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/green/process.py", line 197, in worker
    task = get()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.8/unittest/signals.py", line 36, in __call__
    self.default_handler(signum, frame)
KeyboardInterrupt
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/green/process.py", line 197, in worker
    task = get()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/usr/lib/python3.8/unittest/signals.py", line 36, in __call__
    self.default_handler(signum, frame)
KeyboardInterrupt
  File "/usr/lib/python3.8/threading.py", line 870, in run
    proto_test_result = queue.get()
  File "<string>", line 2, in get
  File "/usr/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 513, in _handle_workers
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    cls._maintain_pool(ctx, Process, processes, pool, inqueue,
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 337, in _maintain_pool
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
    Pool._repopulate_pool_static(ctx, Process, processes, pool,
  File "/usr/lib/python3.8/unittest/signals.py", line 36, in __call__
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 319, in _repopulate_pool_static
    w = Process(ctx, target=worker,
  File "/usr/lib/python3.8/multiprocessing/process.py", line 82, in __init__
    self.default_handler(signum, frame)
KeyboardInterrupt
    assert group is None, 'group argument must be None for now'
AssertionError: group argument must be None for now

**Comment by 3rdIteration** [comment] 2021-02-01 13:44
Looks like it's an issue with your PyOpenCL setup, may be related to the other issue about this.

**Comment by 3rdIteration** [comment] 2021-02-03 18:19
This is a duplicate of https://github.com/3rdIteration/btcrecover/issues/98

It's actually an issue in the unit tests only, so running BTCRecover normally should work fine.

**Closed by 3rdIteration** 2021-02-03 18:19 UTC
