### ISSUE TITLE
GPU Acceleration issues on Windows and Linux

### ISSUE THREAD

**Issue by memreleek** [3rdIteration/btcrecover#98] opened 2021-01-26 01:46 UTC
Hello,

I have read your guides extensively and have had success with the cpu side of things however I am unable to get gpu acceleration to work on multiple machines all with nvidia 2080 gpus. 

I am sure that there is a simple fix that I am missing but I am stumped at this point and have followed your guide atleast 3 times today for each os.

On linux all I seem to be getting is the following warnings and no actual errors:

test_bitcoincore_OpenCL_JTR (__main__.Test08KeyDecryption) ... FAIL

Stdout:
GeForce RTX 2080 SUPER  PyOpenCL Exception:  the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
test_bitcoincore_OpenCL_JTR_unicode (__main__.Test08KeyDecryption) ... FAIL

Stdout:
GeForce RTX 2080 SUPER  PyOpenCL Exception:  the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
test_bitcoincore_OpenCL_JTR_low_interrupt_rate (__main__.Test08KeyDecryption) ... FAIL

Stdout:
GeForce RTX 2080 SUPER  PyOpenCL Exception:  the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
test_bitcoincore_OpenCL_JTR_sli (__main__.Test08KeyDecryption) ... skipped 'requires two identical OpenCL devices'

======================================================================
FAIL: test_bitcoincore_OpenCL_JTR (__main__.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jack/btcr/btcrecover-master/btcrecover/test/test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "/home/jack/btcr/btcrecover-master/btcrecover/test/test_passwords.py", line 1677, in test_bitcoincore_OpenCL_JTR
    self.assertTrue(test_succeeded) #Check that at least one device successfully ran the test
AssertionError: False is not true

Im sure im missing something stupid but I have matched your versions and only used your requirements.txt for dependencies.

Any help would be appreciated. Thanks

**Comment by 3rdIteration** [comment] 2021-01-26 02:02
That's very interesting, haven't seen that deprecation warning before.

What version of PyOpenCL are you running?

**Comment by memreleek** [comment] 2021-01-26 02:16
focal 2019.1.1-1build1 64bit

**Comment by 3rdIteration** [comment] 2021-01-26 02:19
Have you tried with PyOpenCL 2020.1 or 2020.2?

**Comment by memreleek** [comment] 2021-01-26 02:27
I may not have, that might be my issue I thought I did. 8700k, 10900k Ubuntu 20.04 Win 10 190? and 20H2. Hopefully that package is what I needed to change, i messed with numpy and a couple other package versions. Changing versions right now will post back.
Thanks for your time.

**Comment by 3rdIteration** [comment] 2021-01-26 02:28
It should work right out of the box with Ubuntu 20.04 and the pyopencl you get via apt.

**Comment by memreleek** [comment] 2021-01-26 02:33
Thats what I was using, I got the same results again even with the newest version installed via pip.

**Comment by memreleek** [comment] 2021-01-26 02:35
This is a fresh 20.04 LTS install from like an hour ago I also tried disabling securboot and using mbr instead of uefi, fyi.

**Comment by 3rdIteration** [comment] 2021-01-26 03:04
What version of Python?

**Comment by memreleek** [comment] 2021-01-26 03:18
3.8.5

**Comment by 3rdIteration** [comment] 2021-01-31 21:56
So under Windows, what exact PyOpenCL whl file are you running? (I have yet to be able to replicate is on any platform on a few PCs, Windows or Linux)

**Comment by 3rdIteration** [comment] 2021-02-02 14:31
Can't reproduce this with either PyOpenCL 2020.3.1 1.2 or PyOpenCL 2021.1.1

**Comment by 3rdIteration** [comment] 2021-02-03 13:42
So I finally managed to reproduce this in a totally fresh install of Ubuntu 20.04 :) (Still can't reproduce on Windows or with vast.ai)

**Comment by memreleek** [comment] 2021-02-03 15:38
I finally got it working on windows but I was unable to get it working on a fresh ubuntu 20.04. The problem is I cant say for sure what fixed the windows issue. My best guesses are either I had an incorrect version of python, or windows/nvidia power settings. Thanks for looking into this so thoroughly.

**Comment by 3rdIteration** [comment] 2021-02-03 17:16
Good to hear, will leave the issue open until I have improved the unit testing to handle this in a more robust way. I did some digging and it's actually an upstream issue in PyOpenCL, so will get it sorted here first then push a fix back upstream...

**Comment by 3rdIteration** [comment] 2021-07-02 12:58
Resolved in https://github.com/3rdIteration/btcrecover/commit/33c8bb09e319b56f7c1db4f92dab19f4a362bf56

**Closed by 3rdIteration** 2021-07-02 12:58 UTC
Labels: bug
