### ISSUE TITLE
Getting ValueError: malformed node or string on line 176 something in electrum v1 wallet (not sure about version though)

### ISSUE THREAD

**Issue by sc0rp10n-py** [3rdIteration/btcrecover#453] opened 2024-03-13 04:21 UTC
I ran the command for v2 first, it said

`Unsupported Electrum2 wallet seed version 58`

then I tried the Electrum v1 command
it gave me this error
![image](https://github.com/3rdIteration/btcrecover/assets/49873605/e8be5c76-477d-4332-83a1-93129a521680)

i manually went to line 176 in my wallet file, on line 176, its just transaction array. (null parameter is passed in there)

like this
```
"tx_fees": {
        "txn-number": [
            null,
            false,
            1
        ],
        "txn-number": [
            null,
            false,
            1
        ],
        "txn-number": [
            null,
            false,
            3
        ],
        "txn-number": [
            null,
            false,
            2
        ]
    },
```

**Comment by 3rdIteration** [comment] 2024-03-15 10:51
Does btcrecover.py work directly with the file? (As you are trying to use an extract script here)

**Comment by 3rdIteration** [comment] 2024-06-18 00:37
Looks like a duplicate of https://github.com/3rdIteration/btcrecover/issues/457

**Closed by 3rdIteration** 2024-06-18 00:37 UTC
