### ISSUE TITLE
Passwords containing the @ symbol don't get recognized

### ISSUE THREAD

**Issue by naries** [3rdIteration/btcrecover#52] opened 2020-08-17 02:54 UTC
I've been at it for a while now. Every time I try a wallet with a normal password - a wallet without an @ symbol, it works perfectly fine. But any time i try it against my wallet that has a password which contains the @ symbol, it says password search exhausted.

**Comment by 3rdIteration** [comment] 2020-08-20 01:50
Hey so I just created a new blockchain wallet and can't reproduce this at all. I tried it once with the @ symbol in the middle of the password and again with the @ symbol at the beginning. I also tried moving it around the tokenlist and it didn't make any difference.

I have bundled all the test stuff up here:
[testwallets.zip](https://github.com/3rdIteration/btcrecover/files/5100181/testwallets.zip)

Can you try run it on your end and see if it works? The password for each wallet should be the part after the wallet.aes.json- and both will work with the same tokenlist file. (If you have a decent GPU it's really worth enabling OpenCL for this one, as it can solve both wallets in under 10 seconds, as opposed to taking 10 minutes)

If you can't get that working, which kind of wallet are you trying to use? Also, which platform at your on? (I can't reproduce you issue on Windows 10 with Python 3.8.4 64-bit

**Comment by 3rdIteration** [comment] 2020-09-03 15:38
No response for 14 days, closing.

**Closed by 3rdIteration** 2020-09-03 15:38 UTC
