### ISSUE TITLE
https://github.com/3rdIteration/btcrecover/issues/499#issue-2471677697Never heard of it. Have you generated a test wallet to try?

### ISSUE THREAD

**Issue by Layaung230** [3rdIteration/btcrecover#509] opened 2024-10-14 19:49 UTC
Never heard of it. Have you generated a test wallet to try?

_Originally posted by @3rdIteration in https://github.com/3rdIteration/btcrecover/issues/499#issuecomment-2305974472_

**Comment by 3rdIteration** [comment] 2024-10-15 14:33
Duplicate of https://github.com/3rdIteration/btcrecover/issues/499#issuecomment-2305974472

**Closed by 3rdIteration** 2024-10-15 14:33 UTC
