### ISSUE TITLE
Improve Output when a result isn't found so that output is more useful than simply "Password search exhausted" or "Seed Not Found" (Add more descriptive message, point to documentation with some steps to try)

### ISSUE THREAD

**Issue by z3r0d0n3** [3rdIteration/btcrecover#53] opened 2020-08-28 22:25 UTC
Hello,
First of all i want to thank for migrating this to python3 and supporting blockchain v3
so my problem like the title says is that i am feeding with a password list that contains a valid password for my json encrypted wallet and i am receiving Password search exhausted

but i tried to use extract-blockchain-second-hash.py with the same valid password and it was working

but how can i make the btrecover.py to work and give me a success answer,
thank you in advance

python3 extract-blockchain-second-hash.py  ../my.aes.json 
(note your password will not be displayed as you type)
Please enter the Blockchain wallet's main password: 
Double encryption with a second password is not enabled for this wallet

**Comment by 3rdIteration** [comment] 2020-08-31 01:23
Is this just a duplicate of your issue abou the $ character or is this a different password entirely that BTCRecover isn't correctly finding the password for?

**Comment by z3r0d0n3** [comment] 2020-09-02 09:48
is a different one, i found out that $ char is %S, sorry for that,  the BTCRecover does not find correctly the password,
but i managed to write myself a script and using your extract-blockchain-second-hash.py to find out the lost password

**Comment by 3rdIteration** [comment] 2020-09-02 15:16
That's very interesting, so are you able to offer some kind of example password (something like btcr-test-pa$$word) that includes the location of the $ symbol that BTCRecover doesn't find?

Alternatively, can you post the modification you made to the extract script for it to work?

**Comment by z3r0d0n3** [comment] 2020-09-02 16:28
actually the password for the test wallet had no $ in it
i made a file list with 5-6 passwords and had the correct password in there, but btcrecover said Password search exhausted
even if the correct password was present in the list

**Comment by z3r0d0n3** [comment] 2020-09-02 16:31
the modifications of the script extract-blockchain-second-hash.py i made, 
i was just returning true if it was saying  Double encryption with a second password is not enabled for this wallet
that means that the actual password was correct , and in other cases i was returning false
so i run this script in a loop by reading the generated password list from tokens by chunks and running it with multiprocessing to decrease needed time

**Comment by 3rdIteration** [comment] 2020-09-02 19:10
So we're you trying to solve for the main password or second password?

Basically I'm trying to work out if there is actually an issue and if so, what steps can be followed to reproduce it...

**Comment by cissxd** [comment] 2020-09-04 10:05
I also have the same problem, i tried download wallet.aes.json with the extract script, and then use this command

> btcrecover.py --wallet wallet.aes.json --tokenlist token.txt --regex-only "^.{9,10}$"

the token.txt only contain number and alphabet without special symbols.

**Comment by 3rdIteration** [comment] 2020-09-04 12:08
> I also have the same problem, i tried download wallet.aes.json with the extract script, and then use this command
> 
> > btcrecover.py --wallet wallet.aes.json --tokenlist token.txt --regex-only "^.{9,10}$"
> 
> Trying to solving main password
> the token.txt only contain number and alphabet without special symbols.

So can you please create a new wallet with blockchain.com, where you know the password, but where it doesn't work? I have been unable to reproduce any of these errors so far, so am unsure if it's just user error...

**Comment by cissxd** [comment] 2020-09-04 12:29
> So can you please create a new wallet with blockchain.com, where you know the password, but where it doesn't work? I have been unable to reproduce any of these errors so far, so am unsure if it's just user error...
Ok, so i created a fresh new wallet and it works perfectly when i tried to find the password

Oh, looks like i know the problem, when i created password list/token that wrong on purpose, the Password search exhausted is appear. 
Maybe, that Password search exhausted is another indicate that the password can't be found in that list?

**Comment by 3rdIteration** [comment] 2020-09-04 13:35
> > So can you please create a new wallet with blockchain.com, where you know the password, but where it doesn't work? I have been unable to reproduce any of these errors so far, so am unsure if it's just user error...
> 
> Ok, so i created a fresh new wallet and it works perfectly when i tried to find the password
> Oh, looks like i know the problem, when i created password list/token that wrong on purpose, the Password search exhausted is appear.
> Maybe, that Password search exhausted is another indicate that the password can't be found in that list?
> 
> Ah isee, i didn't read the tutorial about if failed, my bad.

If used with a password list, then yes, password search exhausted indicates that all possible passwords were checked with no result. This has come up a few times and it has always ended up being user error, so the issue is basically with the documentation and UI. I think the best bet is to offer some more detailed messages in this instance that also point to the documentation a bit...

**Comment by z3r0d0n3** [comment] 2020-09-07 09:48
i tried it using a password list that contains a valid password and i got Password search exhausted

i was trying to figure out first password,

then i saw your script that decrypts 2nd password,
and if there was not a second password present, but the first password was matching it returns the valid one
so i scripted it a little to accomplish my needs

but the main script that suppose to find the first password fails even if the valid password is present in the list

**Comment by 3rdIteration** [comment] 2020-09-07 18:56
> i tried it using a password list that contains a valid password and i got Password search exhausted
> 
> i was trying to figure out first password,
> 
> then i saw your script that decrypts 2nd password,
> and if there was not a second password present, but the first password was matching it returns the valid one
> so i scripted it a little to accomplish my needs
> 
> but the main script that suppose to find the first password fails even if the valid password is present in the list

I haven't been able to reproduce this situations where it doesn't find the main password, so far it has always come back to user error.

Can you create a test wallet on blockchain.com with a test password that I can use to reproduce this issue? (If you post the wallet file, tokenlist or passwordlist)

**Closed** 2020-12-11 15:01 UTC
Labels: enhancement
